// @flow
import RootTopologyNode from '../object/Root.TopologyNode';
import type { Schema as TopologicalTreeSchema, Root } from '../../schema/topological.tree/1.0.0.type';

function getTemporalTreeFromNode(rootNode: RootTopologyNode): TopologicalTreeSchema {
    const root: Root = rootNode.toNode();

    return {
        label: `Autogenerated (${root.label})`,
        version: '1.0.0',
        root,
    };
}

export default getTemporalTreeFromNode;
