// flow-typed signature: d817d8ab1f1b5954de315631c9058115
// flow-typed version: <<STUB>>/better-ajv-errors_v0.6.7/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'better-ajv-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'better-ajv-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'better-ajv-errors/lib/legacy/helpers' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/json/get-decorated-data-path' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/json/get-meta-from-path' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/json' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/json/utils' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/test-helpers' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/types' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/utils' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/validation-errors/additional-prop' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/validation-errors/base' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/validation-errors/default' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/validation-errors/enum' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/validation-errors' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/legacy/validation-errors/required' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/helpers' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/json/get-decorated-data-path' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/json/get-meta-from-path' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/json' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/json/utils' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/test-helpers' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/types' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/utils' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/validation-errors/additional-prop' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/validation-errors/base' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/validation-errors/default' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/validation-errors/enum' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/validation-errors' {
  declare module.exports: any;
}

declare module 'better-ajv-errors/lib/modern/validation-errors/required' {
  declare module.exports: any;
}

// Filename aliases
declare module 'better-ajv-errors/index' {
  declare module.exports: $Exports<'better-ajv-errors'>;
}
declare module 'better-ajv-errors/index.js' {
  declare module.exports: $Exports<'better-ajv-errors'>;
}
declare module 'better-ajv-errors/lib/legacy/helpers.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/helpers'>;
}
declare module 'better-ajv-errors/lib/legacy/index' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy'>;
}
declare module 'better-ajv-errors/lib/legacy/index.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy'>;
}
declare module 'better-ajv-errors/lib/legacy/json/get-decorated-data-path.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/json/get-decorated-data-path'>;
}
declare module 'better-ajv-errors/lib/legacy/json/get-meta-from-path.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/json/get-meta-from-path'>;
}
declare module 'better-ajv-errors/lib/legacy/json/index' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/json'>;
}
declare module 'better-ajv-errors/lib/legacy/json/index.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/json'>;
}
declare module 'better-ajv-errors/lib/legacy/json/utils.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/json/utils'>;
}
declare module 'better-ajv-errors/lib/legacy/test-helpers.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/test-helpers'>;
}
declare module 'better-ajv-errors/lib/legacy/types.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/types'>;
}
declare module 'better-ajv-errors/lib/legacy/utils.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/utils'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/additional-prop.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors/additional-prop'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/base.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors/base'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/default.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors/default'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/enum.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors/enum'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/index' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/index.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors'>;
}
declare module 'better-ajv-errors/lib/legacy/validation-errors/required.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/legacy/validation-errors/required'>;
}
declare module 'better-ajv-errors/lib/modern/helpers.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/helpers'>;
}
declare module 'better-ajv-errors/lib/modern/index' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern'>;
}
declare module 'better-ajv-errors/lib/modern/index.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern'>;
}
declare module 'better-ajv-errors/lib/modern/json/get-decorated-data-path.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/json/get-decorated-data-path'>;
}
declare module 'better-ajv-errors/lib/modern/json/get-meta-from-path.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/json/get-meta-from-path'>;
}
declare module 'better-ajv-errors/lib/modern/json/index' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/json'>;
}
declare module 'better-ajv-errors/lib/modern/json/index.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/json'>;
}
declare module 'better-ajv-errors/lib/modern/json/utils.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/json/utils'>;
}
declare module 'better-ajv-errors/lib/modern/test-helpers.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/test-helpers'>;
}
declare module 'better-ajv-errors/lib/modern/types.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/types'>;
}
declare module 'better-ajv-errors/lib/modern/utils.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/utils'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/additional-prop.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors/additional-prop'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/base.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors/base'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/default.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors/default'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/enum.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors/enum'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/index' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/index.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors'>;
}
declare module 'better-ajv-errors/lib/modern/validation-errors/required.js' {
  declare module.exports: $Exports<'better-ajv-errors/lib/modern/validation-errors/required'>;
}
