// flow-typed signature: 9cdb145d0de17e5e85fea1569a02494b
// flow-typed version: <<STUB>>/jsnetworkx_v0.3.4/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsnetworkx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsnetworkx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsnetworkx/node/_internals/Arrays' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/clear' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/clone' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/deepcopy' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/deepmerge' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/delegate' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/delegateSync' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/delegateToWorker' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/emitter' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/fillArray' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/forEach' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/gcd' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/genCombinations' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/genPermutations' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/genRange' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/getDefault' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isArrayLike' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isBoolean' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isGraph' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isIterable' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isIterator' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isMap' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isPlainObject' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/isSet' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/items' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/iteritems' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/Map' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/mapIterator' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/mapSequence' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/max' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/message' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/next' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/nodesAreEqual' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/PriorityQueue' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/range' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/Set' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/size' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/someIterator' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/sprintf' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/toIterator' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/toMapFromKeys' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/toObjectFromKeys' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/toObjectFromKV' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/tuple' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/Worker' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/zipIterator' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/_internals/zipSequence' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/centrality/betweenness' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/centrality/eigenvector' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/centrality' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/clique' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/cluster' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/dag' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/graphical' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/isomorphism' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/isomorphism/isomorph' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/operators/binary' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/operators' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/shortestPaths/generic' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/shortestPaths' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/shortestPaths/unweighted' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/algorithms/shortestPaths/weighted' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/browser' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/classes/DiGraph' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/classes/functions' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/classes/Graph' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/classes' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/classes/MultiDiGraph' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/classes/MultiGraph' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/contrib/convert' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/contrib/observer' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/contrib/prepCreateUsing' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/convert' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/drawing' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/drawing/svg' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions/JSNetworkXAlgorithmError' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions/JSNetworkXError' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions/JSNetworkXException' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions/JSNetworkXNoPath' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions/JSNetworkXUnfeasible' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/exceptions/KeyError' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/generators/classic' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/generators/degreeSequence' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/generators' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/generators/randomGraphs' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/generators/small' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/generators/social' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/initializeBrowserWorker' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/relabel' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/worker' {
  declare module.exports: any;
}

declare module 'jsnetworkx/node/WorkerSettings' {
  declare module.exports: any;
}

declare module 'jsnetworkx/transforms/replace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsnetworkx/node/_internals/Arrays.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/Arrays'>;
}
declare module 'jsnetworkx/node/_internals/clear.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/clear'>;
}
declare module 'jsnetworkx/node/_internals/clone.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/clone'>;
}
declare module 'jsnetworkx/node/_internals/deepcopy.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/deepcopy'>;
}
declare module 'jsnetworkx/node/_internals/deepmerge.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/deepmerge'>;
}
declare module 'jsnetworkx/node/_internals/delegate.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/delegate'>;
}
declare module 'jsnetworkx/node/_internals/delegateSync.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/delegateSync'>;
}
declare module 'jsnetworkx/node/_internals/delegateToWorker.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/delegateToWorker'>;
}
declare module 'jsnetworkx/node/_internals/emitter.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/emitter'>;
}
declare module 'jsnetworkx/node/_internals/fillArray.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/fillArray'>;
}
declare module 'jsnetworkx/node/_internals/forEach.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/forEach'>;
}
declare module 'jsnetworkx/node/_internals/gcd.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/gcd'>;
}
declare module 'jsnetworkx/node/_internals/genCombinations.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/genCombinations'>;
}
declare module 'jsnetworkx/node/_internals/genPermutations.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/genPermutations'>;
}
declare module 'jsnetworkx/node/_internals/genRange.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/genRange'>;
}
declare module 'jsnetworkx/node/_internals/getDefault.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/getDefault'>;
}
declare module 'jsnetworkx/node/_internals/index' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals'>;
}
declare module 'jsnetworkx/node/_internals/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals'>;
}
declare module 'jsnetworkx/node/_internals/isArrayLike.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isArrayLike'>;
}
declare module 'jsnetworkx/node/_internals/isBoolean.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isBoolean'>;
}
declare module 'jsnetworkx/node/_internals/isGraph.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isGraph'>;
}
declare module 'jsnetworkx/node/_internals/isIterable.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isIterable'>;
}
declare module 'jsnetworkx/node/_internals/isIterator.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isIterator'>;
}
declare module 'jsnetworkx/node/_internals/isMap.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isMap'>;
}
declare module 'jsnetworkx/node/_internals/isPlainObject.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isPlainObject'>;
}
declare module 'jsnetworkx/node/_internals/isSet.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/isSet'>;
}
declare module 'jsnetworkx/node/_internals/items.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/items'>;
}
declare module 'jsnetworkx/node/_internals/iteritems.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/iteritems'>;
}
declare module 'jsnetworkx/node/_internals/Map.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/Map'>;
}
declare module 'jsnetworkx/node/_internals/mapIterator.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/mapIterator'>;
}
declare module 'jsnetworkx/node/_internals/mapSequence.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/mapSequence'>;
}
declare module 'jsnetworkx/node/_internals/max.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/max'>;
}
declare module 'jsnetworkx/node/_internals/message.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/message'>;
}
declare module 'jsnetworkx/node/_internals/next.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/next'>;
}
declare module 'jsnetworkx/node/_internals/nodesAreEqual.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/nodesAreEqual'>;
}
declare module 'jsnetworkx/node/_internals/PriorityQueue.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/PriorityQueue'>;
}
declare module 'jsnetworkx/node/_internals/range.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/range'>;
}
declare module 'jsnetworkx/node/_internals/Set.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/Set'>;
}
declare module 'jsnetworkx/node/_internals/size.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/size'>;
}
declare module 'jsnetworkx/node/_internals/someIterator.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/someIterator'>;
}
declare module 'jsnetworkx/node/_internals/sprintf.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/sprintf'>;
}
declare module 'jsnetworkx/node/_internals/toIterator.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/toIterator'>;
}
declare module 'jsnetworkx/node/_internals/toMapFromKeys.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/toMapFromKeys'>;
}
declare module 'jsnetworkx/node/_internals/toObjectFromKeys.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/toObjectFromKeys'>;
}
declare module 'jsnetworkx/node/_internals/toObjectFromKV.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/toObjectFromKV'>;
}
declare module 'jsnetworkx/node/_internals/tuple.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/tuple'>;
}
declare module 'jsnetworkx/node/_internals/Worker.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/Worker'>;
}
declare module 'jsnetworkx/node/_internals/zipIterator.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/zipIterator'>;
}
declare module 'jsnetworkx/node/_internals/zipSequence.js' {
  declare module.exports: $Exports<'jsnetworkx/node/_internals/zipSequence'>;
}
declare module 'jsnetworkx/node/algorithms/centrality/betweenness.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/centrality/betweenness'>;
}
declare module 'jsnetworkx/node/algorithms/centrality/eigenvector.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/centrality/eigenvector'>;
}
declare module 'jsnetworkx/node/algorithms/centrality/index' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/centrality'>;
}
declare module 'jsnetworkx/node/algorithms/centrality/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/centrality'>;
}
declare module 'jsnetworkx/node/algorithms/clique.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/clique'>;
}
declare module 'jsnetworkx/node/algorithms/cluster.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/cluster'>;
}
declare module 'jsnetworkx/node/algorithms/dag.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/dag'>;
}
declare module 'jsnetworkx/node/algorithms/graphical.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/graphical'>;
}
declare module 'jsnetworkx/node/algorithms/index' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms'>;
}
declare module 'jsnetworkx/node/algorithms/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms'>;
}
declare module 'jsnetworkx/node/algorithms/isomorphism/index' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/isomorphism'>;
}
declare module 'jsnetworkx/node/algorithms/isomorphism/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/isomorphism'>;
}
declare module 'jsnetworkx/node/algorithms/isomorphism/isomorph.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/isomorphism/isomorph'>;
}
declare module 'jsnetworkx/node/algorithms/operators/binary.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/operators/binary'>;
}
declare module 'jsnetworkx/node/algorithms/operators/index' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/operators'>;
}
declare module 'jsnetworkx/node/algorithms/operators/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/operators'>;
}
declare module 'jsnetworkx/node/algorithms/shortestPaths/generic.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/shortestPaths/generic'>;
}
declare module 'jsnetworkx/node/algorithms/shortestPaths/index' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/shortestPaths'>;
}
declare module 'jsnetworkx/node/algorithms/shortestPaths/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/shortestPaths'>;
}
declare module 'jsnetworkx/node/algorithms/shortestPaths/unweighted.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/shortestPaths/unweighted'>;
}
declare module 'jsnetworkx/node/algorithms/shortestPaths/weighted.js' {
  declare module.exports: $Exports<'jsnetworkx/node/algorithms/shortestPaths/weighted'>;
}
declare module 'jsnetworkx/node/browser.js' {
  declare module.exports: $Exports<'jsnetworkx/node/browser'>;
}
declare module 'jsnetworkx/node/classes/DiGraph.js' {
  declare module.exports: $Exports<'jsnetworkx/node/classes/DiGraph'>;
}
declare module 'jsnetworkx/node/classes/functions.js' {
  declare module.exports: $Exports<'jsnetworkx/node/classes/functions'>;
}
declare module 'jsnetworkx/node/classes/Graph.js' {
  declare module.exports: $Exports<'jsnetworkx/node/classes/Graph'>;
}
declare module 'jsnetworkx/node/classes/index' {
  declare module.exports: $Exports<'jsnetworkx/node/classes'>;
}
declare module 'jsnetworkx/node/classes/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/classes'>;
}
declare module 'jsnetworkx/node/classes/MultiDiGraph.js' {
  declare module.exports: $Exports<'jsnetworkx/node/classes/MultiDiGraph'>;
}
declare module 'jsnetworkx/node/classes/MultiGraph.js' {
  declare module.exports: $Exports<'jsnetworkx/node/classes/MultiGraph'>;
}
declare module 'jsnetworkx/node/contrib/convert.js' {
  declare module.exports: $Exports<'jsnetworkx/node/contrib/convert'>;
}
declare module 'jsnetworkx/node/contrib/observer.js' {
  declare module.exports: $Exports<'jsnetworkx/node/contrib/observer'>;
}
declare module 'jsnetworkx/node/contrib/prepCreateUsing.js' {
  declare module.exports: $Exports<'jsnetworkx/node/contrib/prepCreateUsing'>;
}
declare module 'jsnetworkx/node/convert.js' {
  declare module.exports: $Exports<'jsnetworkx/node/convert'>;
}
declare module 'jsnetworkx/node/drawing/index' {
  declare module.exports: $Exports<'jsnetworkx/node/drawing'>;
}
declare module 'jsnetworkx/node/drawing/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/drawing'>;
}
declare module 'jsnetworkx/node/drawing/svg.js' {
  declare module.exports: $Exports<'jsnetworkx/node/drawing/svg'>;
}
declare module 'jsnetworkx/node/exceptions/index' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions'>;
}
declare module 'jsnetworkx/node/exceptions/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions'>;
}
declare module 'jsnetworkx/node/exceptions/JSNetworkXAlgorithmError.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions/JSNetworkXAlgorithmError'>;
}
declare module 'jsnetworkx/node/exceptions/JSNetworkXError.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions/JSNetworkXError'>;
}
declare module 'jsnetworkx/node/exceptions/JSNetworkXException.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions/JSNetworkXException'>;
}
declare module 'jsnetworkx/node/exceptions/JSNetworkXNoPath.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions/JSNetworkXNoPath'>;
}
declare module 'jsnetworkx/node/exceptions/JSNetworkXUnfeasible.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions/JSNetworkXUnfeasible'>;
}
declare module 'jsnetworkx/node/exceptions/KeyError.js' {
  declare module.exports: $Exports<'jsnetworkx/node/exceptions/KeyError'>;
}
declare module 'jsnetworkx/node/generators/classic.js' {
  declare module.exports: $Exports<'jsnetworkx/node/generators/classic'>;
}
declare module 'jsnetworkx/node/generators/degreeSequence.js' {
  declare module.exports: $Exports<'jsnetworkx/node/generators/degreeSequence'>;
}
declare module 'jsnetworkx/node/generators/index' {
  declare module.exports: $Exports<'jsnetworkx/node/generators'>;
}
declare module 'jsnetworkx/node/generators/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node/generators'>;
}
declare module 'jsnetworkx/node/generators/randomGraphs.js' {
  declare module.exports: $Exports<'jsnetworkx/node/generators/randomGraphs'>;
}
declare module 'jsnetworkx/node/generators/small.js' {
  declare module.exports: $Exports<'jsnetworkx/node/generators/small'>;
}
declare module 'jsnetworkx/node/generators/social.js' {
  declare module.exports: $Exports<'jsnetworkx/node/generators/social'>;
}
declare module 'jsnetworkx/node/index' {
  declare module.exports: $Exports<'jsnetworkx/node'>;
}
declare module 'jsnetworkx/node/index.js' {
  declare module.exports: $Exports<'jsnetworkx/node'>;
}
declare module 'jsnetworkx/node/initializeBrowserWorker.js' {
  declare module.exports: $Exports<'jsnetworkx/node/initializeBrowserWorker'>;
}
declare module 'jsnetworkx/node/relabel.js' {
  declare module.exports: $Exports<'jsnetworkx/node/relabel'>;
}
declare module 'jsnetworkx/node/worker.js' {
  declare module.exports: $Exports<'jsnetworkx/node/worker'>;
}
declare module 'jsnetworkx/node/WorkerSettings.js' {
  declare module.exports: $Exports<'jsnetworkx/node/WorkerSettings'>;
}
declare module 'jsnetworkx/transforms/replace.js' {
  declare module.exports: $Exports<'jsnetworkx/transforms/replace'>;
}
